FROM node:20-alpine

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

EXPOSE 7000

ENV PORT=7000
ENV HOSTNAME="0.0.0.0"
ENV WATCHPACK_POLLING=true

CMD ["npm", "run", "dev", "--", "--hostname", "0.0.0.0", "--port", "7000"]
