"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "ru" | "en" | "kz";

export const translations = {
  ru: {
    sidebar: {
      home: "Главная",
      chat: "ИИ Поиск",
      history: "История",
      favorites: "Избранное",
      profile: "Профиль",
      settings: "Настройки",
      logout: "Выйти",
    },
    theme: {
      light: "Светлая",
      dark: "Тёмная",
      system: "Системная",
    },
    home: {
      badge: "ИИ-навигатор по заведениям Астаны",
      heroTitle1: "Подберём ",
      heroTitle2: "идеальное место",
      heroTitle3: " под ваш запрос",
      heroSubtitle: "Задавайте вопросы на обычном языке. Умный ИИ подберет лучший вариант, покажет честные отзывы, рейтинг и построит удобный маршрут на карте 2GIS.",
      placeholder: "Суши возле Astana IT University до 10 000 ₸...",
      searchBtn: "Найти",
      navMain: "Главная",
      navAI: "ИИ Поиск",
      navHistory: "История",
      navFav: "Избранное",
      navStart: "Начать поиск",
      aboutTag: "О сервисе",
      aboutTitle: "Новый подход к поиску заведений в вашем городе",
      aboutDesc: "City Guide AI избавляет от долгих поисков на картах. Вы просто формулируете желание своими словами — «где романтично поужинать до 15 000 тенге» или «тихое кафе для работы с ноутбуком», а наш алгоритм мгновенно подбирает идеальные места.",
      aboutBtn: "Открыть чат с ИИ",
      ribbonAI: "100% Умный локальный ИИ-поиск",
      ribbon2GIS: "Интеграция с каталогом 2GIS",
      ribbonRoutes: "Маршруты и точки пересадок",
      ribbonReviews: "Честный анализ отзывов",
      catTag: "Категории",
      catTitle: "Популярные направления",
      topPickTag: "Топ выбор",
      topPickTitle: "Популярно прямо сейчас",
      topPickAll: "Все рекомендации",
      recentTitle: "Ваши недавние поиски",
      recentHistory: "История",
      categories: "Категории",
      recentSearches: "Недавние поиски",
      viewAll: "Смотреть все",
      popularNow: "Популярно прямо сейчас",
      stats1Val: "1 000+",
      stats1Label: "Заведений в Астане",
      stats1Sub: "Рестораны, кофейни, бары с точным рейтингом",
      stats2Title: "ИИ Маршруты 2GIS",
      stats2Sub: "Пешком · Авто · Автобусы",
      popularPrompts: [
        "Лучшие суши до 10 000 ₸",
        "Тихое кофейня для работы",
        "Романтический ужин на двоих",
        "Ресторан для большой компании",
        "Панорамный бар с видом на город",
        "Здоровая еда и обеды",
      ],
      catLabels: {
        restaurants: "Рестораны",
        cafes: "Кофейни",
        bars: "Бары & Лаундж",
        fastfood: "Пицца & Суши",
        bakeries: "Кондитерские",
        healthy: "Эко & Веган",
      },
    },
    chat: {
      title: "ИИ Поиск",
      newChat: "Новый чат",
      map: "Карта",
      emptyTitle: "Куда бы вы хотели отправиться?",
      emptySub: "Задайте вопрос на обыкновенном языке — рестораны, суши, тихие кафе для работы или места под ваш бюджет.",
      tryAsking: "Попробуйте спросить…",
      placeholder: "Спросите про рестораны, суши, тихие кафе, места в Астане…",
      locationAttached: "Геопозиция прикреплена — поиск с учетом вашего местоположения",
      enterHelp: "Нажмите Enter для отправки · Shift+Enter для переноса строки",
      foundPlaces: "Найдено мест по вашему запросу:",
      topPick: "Лучший выбор:",
      errorMsg: "К сожалению, по данному запросу ничего не найдено. Попробуйте сформулировать по-другому.",
      voiceStart: "Голосовой ввод",
      voiceStop: "Остановить запись",
      prompts: [
        "Лучшие суши возле Astana IT University до 10 000 ₸",
        "Тихая кофейня с хорошим Wi-Fi для работы",
        "Романтический ужин для двоих",
        "Ресторан для большой компании",
        "Панорамный бар с видом на город",
        "Здоровая еда и полезные обеды",
      ],
    },
    placeCard: {
      topPickBadge: "Лучший выбор",
      match: "совпадение",
      walk: "мин. пешком",
      drive: "мин. на авто",
      compare: "Сравнить",
      selectedForCompare: "Выбрано",
      shareLinkCopied: "Ссылка скопирована в буфер обмена",
      favAdded: "Добавлено в избранное",
      favRemoved: "Удалено из избранного",
      share: "Поделиться",
      showOnMap: "На карте",
      photos: "Фото",
    },
    compareModal: {
      title: "AI Сравнение заведений",
      verdict: "ИИ Вердикт",
      winner: "Лучший вариант",
      bestFor: "Идеально для",
      pros: "Плюсы",
      cons: "Минусы",
      differences: "Главные отличия",
      close: "Закрыть",
      comparingCount: "Сравнение 2GIS мест",
    },
    settings: {
      title: "Настройки",
      subtitle: "Персонализация внешнего вида и локальное хранилище",
      appearance: "Внешний вид",
      visualTheme: "Визуальная тема",
      visualThemeSub: "Переключение между светлой и темной темами",
      localization: "Локализация",
      language: "Язык интерфейса",
      languageSub: "Основной язык приложения и поиска ИИ",
      dataStorage: "Данные и хранилище",
      clearCache: "Очистить локальный кэш",
      clearCacheSub: "Сбрасывает сохраненные данные запросов и карточек мест",
      confirm: "Подтвердить",
      cancel: "Отмена",
      cacheCleared: "Кэш очищен",
      account: "Аккаунт",
      signOut: "Выйти из системы",
      signOutSub: "Завершение текущей активной сессии",
      signedOut: "Вы вышли из системы",
    },
    history: {
      title: "История поисков",
      savedCount: "Сохранено записей:",
      filterPlaceholder: "Фильтр по прошлым запросам...",
      noHistoryTitle: "История пуста",
      noHistorySub: "Ваши ИИ-запросы будут автоматически сохраняться здесь",
      noMatchTitle: "Ничего не найдено",
      noMatchSub: "Попробуйте изменить параметры фильтрации",
      repeatSearch: "Повторить поиск",
    },
    favorites: {
      title: "Избранное",
      savedCount: "Сохранено заведений в вашей коллекции:",
      searchPlaceholder: "Поиск по сохраненным местам...",
      newest: "Сначала новые",
      oldest: "Сначала старые",
      alphabetical: "По алфавиту А–Я",
      emptyTitle: "Список избранного пуст",
      emptySub: "Сохраняйте рестораны и кафе для быстрого доступа",
      savedAgo: "Сохранено",
    },
    profile: {
      title: "Профиль пользователя",
      subtitle: "Управление аккаунтом и аналитика ИИ-поисков",
      totalQueries: "Всего запросов",
      savedPlaces: "Сохраненные места",
      matchScore: "Точность Match",
      daysActive: "Дней в сервисе",
      recentActivity: "Недавняя активность",
      noActivity: "Записи в истории пока отсутствуют.",
    },
    login: {
      welcome: "С возвращением",
      sub: "Войдите в аккаунт для сохранения избранных мест и истории",
      email: "Электронная почта",
      password: "Пароль",
      signingIn: "Выполняется вход...",
      signIn: "Войти",
      noAccount: "Ещё нет аккаунта?",
      createAccount: "Создать аккаунт",
      googleSignIn: "Войти через Google",
      githubSignIn: "Войти через GitHub",
      orEmail: "Или через электронную почту",
      authenticating: "Авторизация...",
    },
    register: {
      title: "Регистрация",
      sub: "Создайте аккаунт, чтобы получать персональные рекомендации и сохранять избранные места",
      fullName: "Имя и фамилия",
      email: "Электронная почта",
      password: "Пароль",
      creatingAccount: "Создание аккаунта...",
      signUp: "Зарегистрироваться",
      hasAccount: "Уже есть аккаунт?",
      signIn: "Войти",
    },
    filters: {
      title: "Фильтры",
      openNow: "Открыто сейчас",
      minRating: "Минимальный рейтинг",
      priceRange: "Бюджет",
      any: "Любой",
      budget: "Бюджетно",
      mid: "Средний",
      premium: "Премиум",
      travelMode: "Передвижение",
      walking: "Пешком",
      driving: "На авто",
      maxTime: "Макс. время в пути",
      maxDistance: "Радиус поиска",
      apply: "Применить",
      reset: "Сбросить",
    },
  },
  en: {
    sidebar: {
      home: "Home",
      chat: "AI Search",
      history: "History",
      favorites: "Favorites",
      profile: "Profile",
      settings: "Settings",
      logout: "Sign Out",
    },
    theme: {
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    home: {
      badge: "AI City Guide & Navigator for Astana",
      heroTitle1: "Find the ",
      heroTitle2: "perfect venue",
      heroTitle3: " for your request",
      heroSubtitle: "Ask in plain natural language. Smart AI finds the best places, analyzes reviews, ratings, and draws turn-by-turn routes on 2GIS map.",
      placeholder: "Sushi near Astana IT University under 10,000 ₸…",
      searchBtn: "Search",
      navMain: "Home",
      navAI: "AI Search",
      navHistory: "History",
      navFav: "Favorites",
      navStart: "Start Search",
      aboutTag: "About Service",
      aboutTitle: "A New Way to Discover Venues in Your City",
      aboutDesc: "City Guide AI eliminates tedious manual searching on maps. Simply express your wish naturally — 'where to have a romantic dinner under 15,000 KZT' or 'a quiet cafe to work with a laptop', and our algorithm recommends ideal venues instantly.",
      aboutBtn: "Open AI Chat",
      ribbonAI: "100% Smart Local AI Search",
      ribbon2GIS: "Deep 2GIS Catalog Integration",
      ribbonRoutes: "Turn Routes & Bus Transfers",
      ribbonReviews: "Honest AI Review Analysis",
      catTag: "Categories",
      catTitle: "Popular Categories",
      topPickTag: "Top Choice",
      topPickTitle: "Popular Right Now",
      topPickAll: "All Recommendations",
      recentTitle: "Your Recent Searches",
      recentHistory: "History",
      categories: "Categories",
      recentSearches: "Recent Searches",
      viewAll: "View All",
      popularNow: "Popular Right Now",
      stats1Val: "1,000+",
      stats1Label: "Venues in Astana",
      stats1Sub: "Restaurants, cafes, bars with verified ratings",
      stats2Title: "2GIS AI Routes",
      stats2Sub: "Pedestrian · Car · Bus Lines",
      popularPrompts: [
        "Best sushi under 10,000 ₸",
        "Quiet coffee shop to work from",
        "Romantic dinner for two",
        "Restaurant for a group",
        "Rooftop bar with city view",
        "Healthy lunch spots",
      ],
      catLabels: {
        restaurants: "Restaurants",
        cafes: "Coffee Shops",
        bars: "Bars & Lounge",
        fastfood: "Pizza & Sushi",
        bakeries: "Bakeries",
        healthy: "Eco & Vegan",
      },
    },
    chat: {
      title: "AI Search",
      newChat: "New chat",
      map: "Map",
      emptyTitle: "Where would you like to go?",
      emptySub: "Ask me anything — sushi, quiet cafes, romantic dinners, group venues, and more.",
      tryAsking: "Try asking…",
      placeholder: "Ask about restaurants, cafes, places in Astana…",
      locationAttached: "Location attached — results will be near you",
      enterHelp: "Press Enter to send · Shift+Enter for new line",
      foundPlaces: "Places found matching your request:",
      topPick: "Top pick:",
      errorMsg: "Unfortunately, no places were found matching this search. Please try a different query.",
      voiceStart: "Voice input",
      voiceStop: "Stop recording",
      prompts: [
        "Best sushi near Astana IT University under 10,000 ₸",
        "Quiet coffee shop with good Wi-Fi to work from",
        "Romantic dinner for two",
        "Restaurant for a group of 8 people",
        "Rooftop bar with a city view",
        "Healthy lunch spots nearby",
      ],
    },
    placeCard: {
      topPickBadge: "Top Pick",
      match: "Match",
      walk: "min walk",
      drive: "min drive",
      compare: "Compare",
      selectedForCompare: "Selected",
      shareLinkCopied: "Link copied to clipboard",
      favAdded: "Added to favorites",
      favRemoved: "Removed from favorites",
      share: "Share",
      showOnMap: "Show on map",
      photos: "Photos",
    },
    compareModal: {
      title: "AI Venue Comparison",
      verdict: "AI Verdict",
      winner: "Top Pick",
      bestFor: "Best for",
      pros: "Pros",
      cons: "Cons",
      differences: "Key Differences",
      close: "Close",
      comparingCount: "Comparing 2GIS places",
    },
    settings: {
      title: "Settings",
      subtitle: "Customize application appearance and local storage",
      appearance: "Appearance",
      visualTheme: "Visual Theme",
      visualThemeSub: "Switch between light and dark modes",
      localization: "Localization",
      language: "Interface Language",
      languageSub: "Default response and search language",
      dataStorage: "Data & Storage",
      clearCache: "Clear Local Cache",
      clearCacheSub: "Flushes locally stored search queries and place metadata",
      confirm: "Confirm",
      cancel: "Cancel",
      cacheCleared: "Cache cleared",
      account: "Account",
      signOut: "Sign Out",
      signOutSub: "End current active user session",
      signedOut: "Signed out",
    },
    history: {
      title: "Search History",
      savedCount: "Saved records:",
      filterPlaceholder: "Filter past queries...",
      noHistoryTitle: "No searches yet",
      noHistorySub: "Your natural language queries will be saved here automatically",
      noMatchTitle: "No matching queries",
      noMatchSub: "Try adjusting your filter search",
      repeatSearch: "Repeat search",
    },
    favorites: {
      title: "Favorites",
      savedCount: "Saved places in your collection:",
      searchPlaceholder: "Search saved places...",
      newest: "Newest first",
      oldest: "Oldest first",
      alphabetical: "Name A–Z",
      emptyTitle: "No favorites yet",
      emptySub: "Save restaurants and cafes to build your personal guide",
      savedAgo: "Saved",
    },
    profile: {
      title: "User Profile",
      subtitle: "Manage account and view AI search analytics",
      totalQueries: "Total Queries",
      savedPlaces: "Saved Places",
      matchScore: "AI Match Score",
      daysActive: "Days Active",
      recentActivity: "Recent Activity",
      noActivity: "No search history recorded yet.",
    },
    login: {
      welcome: "Welcome Back",
      sub: "Sign in to access saved places and search history",
      email: "Email",
      password: "Password",
      signingIn: "Signing in...",
      signIn: "Sign in",
      noAccount: "Don't have an account?",
      createAccount: "Create account",
      googleSignIn: "Sign in with Google",
      githubSignIn: "Sign in with GitHub",
      orEmail: "Or with email",
      authenticating: "Authenticating...",
    },
    register: {
      title: "Create Account",
      sub: "Sign up to get personalized recommendations and save favorite spots",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      creatingAccount: "Creating account...",
      signUp: "Sign up",
      hasAccount: "Already have an account?",
      signIn: "Sign in",
    },
    filters: {
      title: "Filters",
      openNow: "Open now",
      minRating: "Minimum rating",
      priceRange: "Budget",
      any: "Any",
      budget: "Budget",
      mid: "Mid-range",
      premium: "Premium",
      travelMode: "Travel mode",
      walking: "Walking",
      driving: "Driving",
      maxTime: "Max travel time",
      maxDistance: "Search radius",
      apply: "Apply",
      reset: "Reset",
    },
  },
  kz: {
    sidebar: {
      home: "Басты бет",
      chat: "ЖИ Іздеу",
      history: "Тарих",
      favorites: "Таңдаулылар",
      profile: "Профиль",
      settings: "Баптаулар",
      logout: "Шығу",
    },
    theme: {
      light: "Ашық",
      dark: "Күңгірт",
      system: "Жүйелік",
    },
    home: {
      badge: "Астана мекемелері бойынша ЖИ-навигатор",
      heroTitle1: "Сіздің сұранысыңызға ",
      heroTitle2: "тамаша орынды",
      heroTitle3: " тауып береміз",
      heroSubtitle: "Сұрақтарды қарапайым тілде қойыңыз. Ақылды ЖИ ең жақсы нұсқаны таңдап, пікірлер мен рейтингті көрсетеді және 2GIS картасында ыңғайлы бағыт құрады.",
      placeholder: "Astana IT University жанындағы суши 10 000 ₸ дейін…",
      searchBtn: "Іздеу",
      navMain: "Басты бет",
      navAI: "ЖИ Іздеу",
      navHistory: "Тарих",
      navFav: "Таңдаулылар",
      navStart: "Іздеуді бастау",
      aboutTag: "Сервис туралы",
      aboutTitle: "Қалаңыздағы орындарды іздеудің жаңа тәсілі",
      aboutDesc: "City Guide AI карталардағы ұзақ іздеулерден арылтады. Сіз жай ғана өз сөзіңізбен тілек білдіресіз — «15 000 теңгеге дейін романтикалық кешкі ас» немесе «ноутбукпен жұмыс істеуге арналған тыныш кафе», ал біздің алгоритм бірден идеалды орындарды ұсынады.",
      aboutBtn: "ЖИ чатын ашу",
      ribbonAI: "100% Ақылды жергілікті ЖИ-іздеу",
      ribbon2GIS: "2GIS каталогымен интеграция",
      ribbonRoutes: "Бағыттар мен ауысып отыру нүктелері",
      ribbonReviews: "Пікірлерді шынайы талдау",
      catTag: "Санаттар",
      catTitle: "Танымал бағыттар",
      topPickTag: "Үздік таңдау",
      topPickTitle: "Қазір танымал орындар",
      topPickAll: "Барлық ұсыныстар",
      recentTitle: "Соңғы іздеулеріңіз",
      recentHistory: "Тарих",
      categories: "Санаттар",
      recentSearches: "Соңғы іздеулер",
      viewAll: "Барлығын қарау",
      popularNow: "Қазір танымал орындар",
      stats1Val: "1 000+",
      stats1Label: "Астанадағы мекемелер",
      stats1Sub: "Нақты рейтингі бар мейрамханалар мен кафелер",
      stats2Title: "2GIS ЖИ Бағыттары",
      stats2Sub: "Жаяу · Авто · Автобустар",
      popularPrompts: [
        "10 000 ₸ дейінгі үздік суши",
        "Жұмыс үшін тыныш кафе",
        "Екеуге арналған романтикалық кеш",
        "Үлкен компанияға арналған мейрамхана",
        "Қалаға шолу жасайтын бар",
        "Дұрыс тамақ және түскі ас",
      ],
      catLabels: {
        restaurants: "Мейрамханалар",
        cafes: "Кафелер",
        bars: "Барлар & Лаундж",
        fastfood: "Пицца & Суши",
        bakeries: "Кондитерлік",
        healthy: "Эко & Веган",
      },
    },
    chat: {
      title: "ЖИ Іздеу",
      newChat: "Жаңа чат",
      map: "Карта",
      emptyTitle: "Қайда барғыңыз келеді?",
      emptySub: "Кез келген сұрақ қойыңыз — мейрамханалар, суши, тыныш кафелер, бюджетке сай орындар.",
      tryAsking: "Сұрап көріңіз…",
      placeholder: "Астанадағы мейрамханалар, кафелер туралы сұраңыз…",
      locationAttached: "Геопозиция бекітілді — нәтижелер сіздің орналасқан жеріңізді ескереді",
      enterHelp: "Жіберу үшін Enter · Жаңа жол үшін Shift+Enter",
      foundPlaces: "Сұранысыңыз бойынша табылған орындар:",
      topPick: "Үздік таңдау:",
      errorMsg: "Кешіріңіз, осы сұраныс бойынша ештеңе табылмады. Басқаша сұрап көріңіз.",
      voiceStart: "Дауыстық енгізу",
      voiceStop: "Жазуды тоқтату",
      prompts: [
        "Astana IT University жанындағы үздік суши 10 000 ₸ дейін",
        "Жақсы Wi-Fi бар жұмыс үшін тыныш кафе",
        "Екеуге арналған романтикалық кеш",
        "8 адамға арналған мейрамхана",
        "Қала көрінісі бар бар",
        "Жанымдағы дұрыс тамақ орындары",
      ],
    },
    placeCard: {
      topPickBadge: "Үздік таңдау",
      match: "сәйкестік",
      walk: "мин. жаяу",
      drive: "мин. көлікпен",
      compare: "Салыстыру",
      selectedForCompare: "Таңдалды",
      shareLinkCopied: "Сілтеме көшірілді",
      favAdded: "Таңдаулыларға қосылды",
      favRemoved: "Таңдаулылардан жойылды",
      share: "Бөлісу",
      showOnMap: "Картада",
      photos: "Фотолар",
    },
    compareModal: {
      title: "Орындарды ЖИ салыстыру",
      verdict: "ЖИ Вердикті",
      winner: "Үздік нұсқа",
      bestFor: "Ыңғайлы",
      pros: "Артықшылықтары",
      cons: "Кемшіліктері",
      differences: "Негізгі айырмашылықтары",
      close: "Жабу",
      comparingCount: "2GIS орындарын салыстыру",
    },
    settings: {
      title: "Баптаулар",
      subtitle: "Қолданба сыртқы түрін және жергілікті қоймасын баптау",
      appearance: "Сыртқы түр",
      visualTheme: "Визуалды тақырып",
      visualThemeSub: "Ашық және күңгірт тақырыптар арасында ауысу",
      localization: "Локализация",
      language: "Интерфейс тілі",
      languageSub: "Қолданба және ЖИ іздеудің негізгі тілі",
      dataStorage: "Деректер және қойма",
      clearCache: "Жергілікті кэшті тазалау",
      clearCacheSub: "Сақталған іздеу деректерін және орын карточкаларын жояды",
      confirm: "Растау",
      cancel: "Болдырмау",
      cacheCleared: "Кэш тазаланды",
      account: "Аккаунт",
      signOut: "Жүйеден шығу",
      signOutSub: "Ағымдағы белсенді сессияны аяқтау",
      signedOut: "Жүйеден шықтыңыз",
    },
    history: {
      title: "Іздеу тарихы",
      savedCount: "Сақталған жазбалар:",
      filterPlaceholder: "Өткен сұраулар бойынша сүзу...",
      noHistoryTitle: "Тарих бос",
      noHistorySub: "Сіздің ЖИ-сұрауларыңыз автоматты түрде осында сақталады",
      noMatchTitle: "Ештеңе табылмады",
      noMatchSub: "Сүзу параметрлерін өзгертіп көріңіз",
      repeatSearch: "Іздеуді қайталау",
    },
    favorites: {
      title: "Таңдаулылар",
      savedCount: "Жинағыңыздағы сақталған орындар:",
      searchPlaceholder: "Сақталған орындарды іздеу...",
      newest: "Алдымен жаңалары",
      oldest: "Алдымен ескілері",
      alphabetical: "Алфавит бойынша А–Я",
      emptyTitle: "Таңдаулылар тізімі бос",
      emptySub: "Тез қол жеткізу үшін мейрамханалар мен кафелерді сақтаңыз",
      savedAgo: "Сақталды",
    },
    profile: {
      title: "Пайдаланушы профилі",
      subtitle: "Аккаунтты басқару және ЖИ іздеу аналитикасы",
      totalQueries: "Барлық сұраулар",
      savedPlaces: "Сақталған орындар",
      matchScore: "Сәйкестік дәлдігі",
      daysActive: "Қызметтегі күндер",
      recentActivity: "Соңғы белсенділік",
      noActivity: "Тарихта жазбалар әлі жоқ.",
    },
    login: {
      welcome: "Қайта келдіңіз",
      sub: "Таңдаулы орындар мен тарихқа қол жеткізу үшін кіріңіз",
      email: "Электрондық пошта",
      password: "Құпия сөз",
      signingIn: "Кіру орындалуда...",
      signIn: "Кіру",
      noAccount: "Аккаунтыңыз жоқ па?",
      createAccount: "Аккаунт жасау",
      googleSignIn: "Google арқылы кіру",
      githubSignIn: "GitHub арқылы кіру",
      orEmail: "Немесе пошта арқылы",
      authenticating: "Авторизациялануда...",
    },
    register: {
      title: "Тіркелу",
      sub: "Жеке ұсыныстар алу және таңдаулы орындарды сақтау үшін аккаунт жасаңыз",
      fullName: "Аты-жөні",
      email: "Электрондық пошта",
      password: "Құпия сөз",
      creatingAccount: "Аккаунт жасалуда...",
      signUp: "Тіркелу",
      hasAccount: "Аккаунтыңыз бар ма?",
      signIn: "Кіру",
    },
    filters: {
      title: "Сүзгілер",
      openNow: "Қазір ашық",
      minRating: "Ең төменгі рейтинг",
      priceRange: "Бюджет",
      any: "Кез келген",
      budget: "Бюджеттік",
      mid: "Орташа",
      premium: "Премиум",
      travelMode: "Қозғалыс режимі",
      walking: "Жаяу",
      driving: "Көлікпен",
      maxTime: "Ең ұзақ жол уақыты",
      maxDistance: "Іздеу радиусы",
      apply: "Қолдану",
      reset: "Сіфырлау",
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations["ru"];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ru");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("app_language") as Language;
      if (saved === "ru" || saved === "en" || saved === "kz") {
        setLanguageState(saved);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("app_language", lang);
    }
  };

  const value = {
    language,
    setLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
