"use client";

import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "ru" | "en" | "kz";

export const translations = {
  ru: {
    sidebar: {
      home: "Главная",
      chat: "ИИ Поиск",
      history: "История",
      favorites: "Избранное",
      profile: "Профиль",
      settings: "Настройки",
      logout: "Выйти",
    },
    theme: {
      light: "Светлая",
      dark: "Тёмная",
      system: "Системная",
    },
    home: {
      badge: "Умный ИИ-поиск заведений в Астане",
      heroTitle1: "Найдите ",
      heroTitle2: "идеальное место",
      heroTitle3: "в Астане",
      heroSubtitle: "Задавайте вопросы на обычном языке. ИИ подберет, оценит и покажет на карте лучшие заведения под ваш бюджет.",
      placeholder: "Суши возле Astana IT University до 10 000 ₸…",
      searchBtn: "Найти",
      categories: "Категории",
      recentSearches: "Недавние поиски",
      viewAll: "Все запросы",
      popularNow: "Популярное сейчас",
      popularPrompts: [
        "Лучшие суши до 10 000 ₸",
        "Тихое кофейня для работы",
        "Романтический ужин на двоих",
        "Ресторан для большой компании",
        "Панорамный бар с видом на город",
        "Здоровая еда и обеды",
      ],
      catLabels: {
        restaurants: "Рестораны",
        cafes: "Кафе",
        bars: "Бары",
        fastfood: "Фастфуд",
        bakeries: "Пекарни",
        healthy: "Здоровая еда",
      },
    },
    chat: {
      title: "ИИ Поиск",
      newChat: "Новый чат",
      map: "Карта",
      emptyTitle: "Куда бы вы хотели отправиться?",
      emptySub: "Задайте вопрос на обыкновенном языке — рестораны, суши, тихие кафе для работы или места под ваш бюджет.",
      tryAsking: "Попробуйте спросить…",
      placeholder: "Спросите про рестораны, суши, тихие кафе, места в Астане…",
      locationAttached: "Геопозиция прикреплена — поиск с учетом вашего местоположения",
      enterHelp: "Нажмите Enter для отправки · Shift+Enter для переноса строки",
      foundPlaces: "Найдено мест по вашему запросу:",
      topPick: "Лучший выбор:",
      errorMsg: "К сожалению, по данному запросу ничего не найдено. Попробуйте сформулировать по-другому.",
      voiceStart: "Голосовой ввод",
      voiceStop: "Остановить запись",
      prompts: [
        "Лучшие суши возле Astana IT University до 10 000 ₸",
        "Тихая кофейня с хорошим Wi-Fi для работы",
        "Романтический ужин для двоих",
        "Ресторан для большой компании",
        "Панорамный бар с видом на город",
        "Здоровая еда и полезные обеды",
      ],
    },
    placeCard: {
      topPickBadge: "Лучший выбор",
      match: "совпадение",
      walk: "мин. пешком",
      shareLinkCopied: "Ссылка скопирована в буфер обмена",
      favAdded: "Добавлено в избранное",
      favRemoved: "Удалено из избранного",
      share: "Поделиться",
      showOnMap: "На карте",
      photos: "Фото",
    },
    settings: {
      title: "Настройки",
      subtitle: "Персонализация внешнего вида и локальное хранилище",
      appearance: "Внешний вид",
      visualTheme: "Визуальная тема",
      visualThemeSub: "Переключение между светлой и темной темами",
      localization: "Локализация",
      language: "Язык интерфейса",
      languageSub: "Основной язык приложения и поиска ИИ",
      dataStorage: "Данные и хранилище",
      clearCache: "Очистить локальный кэш",
      clearCacheSub: "Сбрасывает сохраненные данные запросов и карточек мест",
      confirm: "Подтвердить",
      cancel: "Отмена",
      cacheCleared: "Кэш очищен",
      account: "Аккаунт",
      signOut: "Выйти из системы",
      signOutSub: "Завершение текущей активной сессии",
      signedOut: "Вы вышли из системы",
    },
    history: {
      title: "История поисков",
      savedCount: "Сохранено записей:",
      filterPlaceholder: "Фильтр по прошлым запросам...",
      noHistoryTitle: "История пуста",
      noHistorySub: "Ваши ИИ-запросы будут автоматически сохраняться здесь",
      noMatchTitle: "Ничего не найдено",
      noMatchSub: "Попробуйте изменить параметры фильтрации",
      repeatSearch: "Повторить поиск",
    },
    favorites: {
      title: "Избранное",
      savedCount: "Сохранено заведений в вашей коллекции:",
      searchPlaceholder: "Поиск по сохраненным местам...",
      newest: "Сначала новые",
      oldest: "Сначала старые",
      alphabetical: "По алфавиту А–Я",
      emptyTitle: "Список избранного пуст",
      emptySub: "Сохраняйте рестораны и кафе для быстрого доступа",
      savedAgo: "Сохранено",
    },
    profile: {
      title: "Профиль пользователя",
      subtitle: "Управление аккаунтом и аналитика ИИ-поисков",
      totalQueries: "Всего запросов",
      savedPlaces: "Сохраненные места",
      matchScore: "Точность Match",
      daysActive: "Дней в сервисе",
      recentActivity: "Недавняя активность",
      noActivity: "Записи в истории пока отсутствуют.",
    },
    login: {
      welcome: "С возвращением",
      sub: "Войдите в аккаунт для сохранения избранных мест и истории",
      email: "Электронная почта",
      password: "Пароль",
      signingIn: "Выполняется вход...",
      signIn: "Войти",
      noAccount: "Ещё нет аккаунта?",
      createAccount: "Создать аккаунт",
    },
    register: {
      title: "Регистрация",
      sub: "Создайте аккаунт, чтобы получать персональные рекомендации и сохранять избранные места",
      fullName: "Имя и фамилия",
      email: "Электронная почта",
      password: "Пароль",
      creatingAccount: "Создание аккаунта...",
      signUp: "Зарегистрироваться",
      hasAccount: "Уже есть аккаунт?",
      signIn: "Войти",
    },
    filters: {
      title: "Фильтры",
      openNow: "Открыто сейчас",
      minRating: "Минимальный рейтинг",
      priceRange: "Бюджет",
      any: "Любой",
      budget: "Бюджетно",
      mid: "Средний",
      premium: "Премиум",
      apply: "Применить",
      reset: "Сбросить",
    },
  },
  en: {
    sidebar: {
      home: "Home",
      chat: "AI Search",
      history: "History",
      favorites: "Favorites",
      profile: "Profile",
      settings: "Settings",
      logout: "Sign Out",
    },
    theme: {
      light: "Light",
      dark: "Dark",
      system: "System",
    },
    home: {
      badge: "AI-Powered Smart Search for Astana",
      heroTitle1: "Find the ",
      heroTitle2: "perfect place",
      heroTitle3: "in Astana",
      heroSubtitle: "Ask in natural language. Our AI finds, ranks, and maps the best restaurants and cafes for your budget.",
      placeholder: "Sushi near Astana IT University under 10,000 ₸…",
      searchBtn: "Search",
      categories: "Categories",
      recentSearches: "Recent Searches",
      viewAll: "View all",
      popularNow: "Popular Now",
      popularPrompts: [
        "Best sushi under 10,000 ₸",
        "Quiet coffee shop to work from",
        "Romantic dinner for two",
        "Restaurant for a group",
        "Rooftop bar with a view",
        "Healthy lunch spots",
      ],
      catLabels: {
        restaurants: "Restaurants",
        cafes: "Cafes",
        bars: "Bars",
        fastfood: "Fast Food",
        bakeries: "Bakeries",
        healthy: "Healthy",
      },
    },
    chat: {
      title: "AI Search",
      newChat: "New chat",
      map: "Map",
      emptyTitle: "Where would you like to go?",
      emptySub: "Ask me anything — sushi, quiet cafes, romantic dinners, group venues, and more.",
      tryAsking: "Try asking…",
      placeholder: "Ask about restaurants, cafes, places in Astana…",
      locationAttached: "Location attached — results will be near you",
      enterHelp: "Press Enter to send · Shift+Enter for new line",
      foundPlaces: "Places found matching your request:",
      topPick: "Top pick:",
      errorMsg: "Unfortunately, no places were found matching this search. Please try a different query.",
      voiceStart: "Voice input",
      voiceStop: "Stop recording",
      prompts: [
        "Best sushi near Astana IT University under 10,000 ₸",
        "Quiet coffee shop with good Wi-Fi to work from",
        "Romantic dinner for two",
        "Restaurant for a group of 8 people",
        "Rooftop bar with a city view",
        "Healthy lunch spots nearby",
      ],
    },
    placeCard: {
      topPickBadge: "Top Pick",
      match: "Match",
      walk: "min walk",
      shareLinkCopied: "Link copied to clipboard",
      favAdded: "Added to favorites",
      favRemoved: "Removed from favorites",
      share: "Share",
      showOnMap: "Show on map",
      photos: "Photos",
    },
    settings: {
      title: "Settings",
      subtitle: "Customize application appearance and local storage",
      appearance: "Appearance",
      visualTheme: "Visual Theme",
      visualThemeSub: "Switch between light and dark modes",
      localization: "Localization",
      language: "Interface Language",
      languageSub: "Default response and search language",
      dataStorage: "Data & Storage",
      clearCache: "Clear Local Cache",
      clearCacheSub: "Flushes locally stored search queries and place metadata",
      confirm: "Confirm",
      cancel: "Cancel",
      cacheCleared: "Cache cleared",
      account: "Account",
      signOut: "Sign Out",
      signOutSub: "End current active user session",
      signedOut: "Signed out",
    },
    history: {
      title: "Search History",
      savedCount: "Saved records:",
      filterPlaceholder: "Filter past queries...",
      noHistoryTitle: "No searches yet",
      noHistorySub: "Your natural language queries will be saved here automatically",
      noMatchTitle: "No matching queries",
      noMatchSub: "Try adjusting your filter search",
      repeatSearch: "Repeat search",
    },
    favorites: {
      title: "Favorites",
      savedCount: "Saved places in your collection:",
      searchPlaceholder: "Search saved places...",
      newest: "Newest first",
      oldest: "Oldest first",
      alphabetical: "Name A–Z",
      emptyTitle: "No favorites yet",
      emptySub: "Save restaurants and cafes to build your personal guide",
      savedAgo: "Saved",
    },
    profile: {
      title: "User Profile",
      subtitle: "Manage account and view AI search analytics",
      totalQueries: "Total Queries",
      savedPlaces: "Saved Places",
      matchScore: "AI Match Score",
      daysActive: "Days Active",
      recentActivity: "Recent Activity",
      noActivity: "No search history recorded yet.",
    },
    login: {
      welcome: "Welcome Back",
      sub: "Sign in to access saved places and search history",
      email: "Email",
      password: "Password",
      signingIn: "Signing in...",
      signIn: "Sign in",
      noAccount: "Don't have an account?",
      createAccount: "Create account",
    },
    register: {
      title: "Create Account",
      sub: "Sign up to get personalized recommendations and save favorite spots",
      fullName: "Full Name",
      email: "Email",
      password: "Password",
      creatingAccount: "Creating account...",
      signUp: "Sign up",
      hasAccount: "Already have an account?",
      signIn: "Sign in",
    },
    filters: {
      title: "Filters",
      openNow: "Open now",
      minRating: "Minimum rating",
      priceRange: "Budget",
      any: "Any",
      budget: "Budget",
      mid: "Mid-range",
      premium: "Premium",
      apply: "Apply",
      reset: "Reset",
    },
  },
  kz: {
    sidebar: {
      home: "Басты бет",
      chat: "ЖИ Іздеу",
      history: "Тарих",
      favorites: "Таңдаулылар",
      profile: "Профиль",
      settings: "Баптаулар",
      logout: "Шығу",
    },
    theme: {
      light: "Ашық",
      dark: "Күңгірт",
      system: "Жүйелік",
    },
    home: {
      badge: "Астанадағы ЖИ-негізіндегі ақылды іздеу",
      heroTitle1: "Табыңыз ",
      heroTitle2: "тамаша орынды",
      heroTitle3: "Астанада",
      heroSubtitle: "Сұрақтарды қарапайым тілде қойыңыз. ЖИ бюджетіңізге сай ең жақсы мекемелерді тауып, бағалайды.",
      placeholder: "Astana IT University жанындағы суши 10 000 ₸ дейін…",
      searchBtn: "Іздеу",
      categories: "Санаттар",
      recentSearches: "Соңғы іздеулер",
      viewAll: "Барлығы",
      popularNow: "Қазір танымал",
      popularPrompts: [
        "10 000 ₸ дейінгі үздік суши",
        "Жұмыс үшін тыныш кафе",
        "Екеуге арналған романтикалық кеш",
        "Үлкен компанияға арналған мейрамхана",
        "Қалаға шолу жасайтын бар",
        "Дұрыс тамақ және түскі ас",
      ],
      catLabels: {
        restaurants: "Мейрамханалар",
        cafes: "Кафелер",
        bars: "Барлар",
        fastfood: "Фастфуд",
        bakeries: "Нанханалар",
        healthy: "Дұрыс тамақ",
      },
    },
    chat: {
      title: "ЖИ Іздеу",
      newChat: "Жаңа чат",
      map: "Карта",
      emptyTitle: "Қайда барғыңыз келеді?",
      emptySub: "Кез келген сұрақ қойыңыз — мейрамханалар, суши, тыныш кафелер, бюджетке сай орындар.",
      tryAsking: "Сұрап көріңіз…",
      placeholder: "Астанадағы мейрамханалар, кафелер туралы сұраңыз…",
      locationAttached: "Геопозиция бекітілді — нәтижелер сіздің орналасқан жеріңізді ескереді",
      enterHelp: "Жіберу үшін Enter · Жаңа жол үшін Shift+Enter",
      foundPlaces: "Сұранысыңыз бойынша табылған орындар:",
      topPick: "Үздік таңдау:",
      errorMsg: "Кешіріңіз, осы сұраныс бойынша ештеңе табылмады. Басқаша сұрап көріңіз.",
      voiceStart: "Дауыстық енгізу",
      voiceStop: "Жазуды тоқтату",
      prompts: [
        "Astana IT University жанындағы үздік суши 10 000 ₸ дейін",
        "Жақсы Wi-Fi бар жұмыс үшін тыныш кафе",
        "Екеуге арналған романтикалық кеш",
        "8 адамға арналған мейрамхана",
        "Қала көрінісі бар бар",
        "Жанымдағы дұрыс тамақ орындары",
      ],
    },
    placeCard: {
      topPickBadge: "Үздік таңдау",
      match: "сәйкестік",
      walk: "мин. жаяу",
      shareLinkCopied: "Сілтеме буферге көшірілді",
      favAdded: "Таңдаулыларға қосылды",
      favRemoved: "Таңдаулылардан жойылды",
      share: "Бөлісу",
      showOnMap: "Картада",
      photos: "Суреттер",
    },
    settings: {
      title: "Баптаулар",
      subtitle: "Қолданба сыртқы түрін және жергілікті қоймасын баптау",
      appearance: "Сыртқы түр",
      visualTheme: "Визуалды тақырып",
      visualThemeSub: "Ашық және күңгірт тақырыптар арасында ауысу",
      localization: "Локализация",
      language: "Интерфейс тілі",
      languageSub: "Қолданба және ЖИ іздеудің негізгі тілі",
      dataStorage: "Деректер және қойма",
      clearCache: "Жергілікті кэшті тазалау",
      clearCacheSub: "Сақталған іздеу деректерін және орын карточкаларын жояды",
      confirm: "Растау",
      cancel: "Болдырмау",
      cacheCleared: "Кэш тазаланды",
      account: "Аккаунт",
      signOut: "Жүйеден шығу",
      signOutSub: "Ағымдағы белсенді сессияны аяқтау",
      signedOut: "Жүйеден шықтыңыз",
    },
    history: {
      title: "Іздеу тарихы",
      savedCount: "Сақталған жазбалар:",
      filterPlaceholder: "Өткен сұраулар бойынша сүзу...",
      noHistoryTitle: "Тарих бос",
      noHistorySub: "Сіздің ЖИ-сұрауларыңыз автоматты түрде осында сақталады",
      noMatchTitle: "Ештеңе табылмады",
      noMatchSub: "Сүзу параметрлерін өзгертіп көріңіз",
      repeatSearch: "Іздеуді қайталау",
    },
    favorites: {
      title: "Таңдаулылар",
      savedCount: "Жинағыңыздағы сақталған орындар:",
      searchPlaceholder: "Сақталған орындарды іздеу...",
      newest: "Алдымен жаңалары",
      oldest: "Алдымен ескілері",
      alphabetical: "Алфавит бойынша А–Я",
      emptyTitle: "Таңдаулылар тізімі бос",
      emptySub: "Тез қол жеткізу үшін мейрамханалар мен кафелерді сақтаңыз",
      savedAgo: "Сақталды",
    },
    profile: {
      title: "Пайдаланушы профилі",
      subtitle: "Аккаунтты басқару және ЖИ іздеу аналитикасы",
      totalQueries: "Барлық сұраулар",
      savedPlaces: "Сақталған орындар",
      matchScore: "Сәйкестік дәлдігі",
      daysActive: "Қызметтегі күндер",
      recentActivity: "Соңғы белсенділік",
      noActivity: "Тарихта жазбалар әлі жоқ.",
    },
    login: {
      welcome: "Қайта келдіңіз",
      sub: "Таңдаулы орындар мен тарихқа қол жеткізу үшін кіріңіз",
      email: "Электрондық пошта",
      password: "Құпия сөз",
      signingIn: "Кіру орындалуда...",
      signIn: "Кіру",
      noAccount: "Аккаунтыңыз жоқ па?",
      createAccount: "Аккаунт жасау",
    },
    register: {
      title: "Тіркелу",
      sub: "Жеке ұсыныстар алу және таңдаулы орындарды сақтау үшін аккаунт жасаңыз",
      fullName: "Аты-жөні",
      email: "Электрондық пошта",
      password: "Құпия сөз",
      creatingAccount: "Аккаунт жасалуда...",
      signUp: "Тіркелу",
      hasAccount: "Аккаунтыңыз бар ма?",
      signIn: "Кіру",
    },
    filters: {
      title: "Сүзгілер",
      openNow: "Қазір ашық",
      minRating: "Ең төменгі рейтинг",
      priceRange: "Бюджет",
      any: "Кез келген",
      budget: "Бюджеттік",
      mid: "Орташа",
      premium: "Премиум",
      apply: "Қолдану",
      reset: "Сіфырлау",
    },
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: typeof translations["ru"];
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguageState] = useState<Language>("ru");

  useEffect(() => {
    if (typeof window !== "undefined") {
      const saved = localStorage.getItem("app_language") as Language;
      if (saved === "ru" || saved === "en" || saved === "kz") {
        setLanguageState(saved);
      }
    }
  }, []);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    if (typeof window !== "undefined") {
      localStorage.setItem("app_language", lang);
    }
  };

  const value = {
    language,
    setLanguage,
    t: translations[language],
  };

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
